// ============ STATE ============
const state = {
  tool: 'select',
  map: { src: null, width: 0, height: 0 },
  grid: { enabled: true, size: 50 },
  view: { zoom: 1, panX: 0, panY: 0 },
  tokens: [],
  characters: [],
  monsters: [],
  selectedTokenId: null,
  nextId: 1,
  isPanning: false,
  panStart: { x: 0, y: 0, viewX: 0, viewY: 0 },
  draggingToken: null,
  dragOffset: { x: 0, y: 0 },
  isDrawing: false,
  lastDrawPos: null,
  drawSettings: { color: '#d4a574', size: 12, opacity: 85 },
  shapes: [],
  shapeSettings: { type: 'rect', layer: 'front' },
  shapeStart: null,
  shapePreview: null,
  measureStart: null,
  measureLabel: null,
  modalImages: { token: null, char: null, mon: null },
  modalColors: { token: '#d4a574', char: '#7ba3c9', mon: '#c97878' },
  editingId: { token: null, char: null, mon: null },
  initiative: [],
  initIndex: 0,
  initRound: 1,
  contextTokenId: null,
  hpModalTokenId: null,
  renameTokenId: null,
  eventLog: [],
  logFilter: 'all',
  expanded: { characters: new Set(), monsters: new Set() },
  lootFilter: 'all',
  selectedLootId: null,
  sidebarLeftCollapsed: false,
  sidebarRightCollapsed: false,
  selectedDice: 20,
  diceHistory: [],
  lastDiceRoll: null,
  lastTableRoll: null,
  lastTokenPlaced: null,
  activeAtmId: null,
};

const COLORS = ['#d4a574', '#c97878', '#7ba3c9', '#7fa869', '#b88ad4', '#d4c878', '#d48a78', '#78c9b8', '#c978a8', '#8a8078'];

const CONDITIONS = [
  { id: 'blinded', name: 'Ослеплён', icon: '👁', color: '#6b7280' },
  { id: 'charmed', name: 'Очарован', icon: '💖', color: '#ec4899' },
  { id: 'deafened', name: 'Оглох', icon: '🔇', color: '#6b7280' },
  { id: 'frightened', name: 'Испуган', icon: '😨', color: '#a855f7' },
  { id: 'grappled', name: 'Схвачен', icon: '🤝', color: '#f59e0b' },
  { id: 'incapacitated', name: 'Недееспособен', icon: '💫', color: '#6b7280' },
  { id: 'invisible', name: 'Невидимый', icon: '👻', color: '#94a3b8' },
  { id: 'paralyzed', name: 'Парализован', icon: '⚡', color: '#eab308' },
  { id: 'petrified', name: 'Окаменел', icon: '🗿', color: '#78716c' },
  { id: 'poisoned', name: 'Отравлен', icon: '☠', color: '#22c55e' },
  { id: 'prone', name: 'Сбит с ног', icon: '⬇', color: '#78716c' },
  { id: 'restrained', name: 'Опутан', icon: '⛓', color: '#b45309' },
  { id: 'stunned', name: 'Оглушён', icon: '💥', color: '#f97316' },
  { id: 'unconscious', name: 'Без сознания', icon: '💤', color: '#475569' },
  { id: 'concentrating', name: 'Концентрация', icon: '🎯', color: '#3b82f6' },
  { id: 'blessed', name: 'Благословлён', icon: '✨', color: '#fbbf24' },
  { id: 'custom', name: 'Своё состояние', icon: '⚙', color: '#d4a574' },
];

const LOG_TYPES = {
  all: { label: 'Все', icon: '📋' },
  system: { label: 'Система', icon: '⚙' },
  token: { label: 'Токены', icon: '⊙' },
  combat: { label: 'Бой', icon: '⚔' },
  character: { label: 'Герои', icon: '👤' },
  monster: { label: 'Монстры', icon: '👹' },
  loot: { label: 'Добыча', icon: '💎' },
  dice: { label: 'Кубики', icon: '🎲' },
  map: { label: 'Карта', icon: '🗺' },
  atm: { label: 'Атмосфера', icon: '🎭' },
};

const ATMOSPHERE = {
  dungeon: [
    { id: 'd1', icon: '🕯', name: 'Сырой коридор', text: 'Воздух пропитан запахом сырости и вековой пыли. Факелы трещат, отбрасывая пляшущие тени на влажные стены. Где-то вдалеке слышен размеренный стук капель.' },
    { id: 'd2', icon: '💀', name: 'Заброшенный склеп', text: 'Ряды каменных саркофагов уходят в темноту. Паутина свисает с потолка гирляндами. Воздух тяжёлый, с привкусом тлена.' },
    { id: 'd3', icon: '🔥', name: 'Зал с лавой', text: 'Жар обжигает лицо. Внизу медленно течёт река раскалённой лавы, освещая всё багровым светом. Воздух дрожит от жара.' },
    { id: 'd4', icon: '💧', name: 'Затопленная камера', text: 'Вода по щиколотку, ледяная и мутная. Эхо ваших шагов многократно отражается от сводов. Уровень воды медленно поднимается.' },
    { id: 'd5', icon: '🕸', name: 'Логово паука', text: 'Липкая паутина повсюду. В коконах под потолком что-то шевелится. Из темноты доносится тихое шуршание множества ног.' },
    { id: 'd6', icon: '⛓', name: 'Застенок', text: 'Ржавые кандалы свисают со стен. На полу — бурые пятна. В воздухе витает запах крови и страха.' },
  ],
  nature: [
    { id: 'n1', icon: '🌲', name: 'Древний лес', text: 'Вековые деревья смыкаются над головой. Воздух напоен запахом хвои и прелой листвы. Под ногами шуршит невидимая мелкая живность.' },
    { id: 'n2', icon: '🏔', name: 'Горный перевал', text: 'Холодный ветер режет лицо. Под ногами осыпаются камни, уходя в бездну. Вдали видны заснеженные пики.' },
    { id: 'n3', icon: '🌊', name: 'Морской берег', text: 'Солёные брызги летят в лицо. Волны с шумом разбиваются о скалы. Крики чаек заглушают всё остальное.' },
    { id: 'n4', icon: '🏜', name: 'Пустыня', text: 'Нещадное солнце палит с самого утра. Песок скрипит под ногами, жар поднимается от земли волнами.' },
    { id: 'n5', icon: '🌫', name: 'Туманные топи', text: 'Густой туман стелется над болотом. Под ногами хлюпает предательская жижа. Воздух тяжёлый, с запахом гнили.' },
    { id: 'n6', icon: '🌸', name: 'Цветущий луг', text: 'Бесконечное море цветов колышется на тёплом ветру. Пчёлы жужжат, бабочки порхают. Солнце пригревает.' },
  ],
  settlement: [
    { id: 's1', icon: '🍺', name: 'Шумная таверна', text: 'Гул голосов, звон кружек, треск очага. Пахнет жареным мясом, элем и потом. У камина кто-то наигрывает на лютне.' },
    { id: 's2', icon: '⛪', name: 'Храм', text: 'Высокие своды, витражи, пропускающие цветные лучи света. Тихое пение жрецов, запах ладана.' },
    { id: 's3', icon: '🏪', name: 'Рынок', text: 'Галдёж торговцев, крики зазывал, блеяние овец. Пахнет специями, свежей рыбой и навозом.' },
    { id: 's4', icon: '🏰', name: 'Тронный зал', text: 'Мраморные колонны, гобелены на стенах, эхо шагов. Стражники в блестящих доспехах стоят неподвижно.' },
    { id: 's5', icon: '🌃', name: 'Ночные улицы', text: 'Факелы мерцают в нишах, отбрасывая длинные тени. Шаги эхом разносятся по пустым мостовым.' },
    { id: 's6', icon: '🎪', name: 'Ярмарка', text: 'Яркие шатры, запах сахарной ваты и жареных каштанов. Цирк уродцев зазывает публику, жонглёр показывает фокусы.' },
  ],
  combat: [
    { id: 'c1', icon: '⚔', name: 'Начало битвы', text: 'Металл звенит о металл. Крики ярости и боли сливаются в единый гул. Пыль поднимается от топота ног.' },
    { id: 'c2', icon: '🩸', name: 'Разгар сражения', text: 'Все вокруг движутся в бешеном темпе. Рука сама находит рукоять меча, ноги уклоняются от ударов. Адреналин заглушает всё.' },
    { id: 'c3', icon: '🏹', name: 'Засада', text: 'Свист стрел! Первый крик, второй. Из кустов выскакивают фигуры. Паника, неразбериха.' },
    { id: 'c4', icon: '🐉', name: 'Битва с боссом', text: 'Перед вами возвышается существо из кошмаров. Земля дрожит от его шагов. Ваши союзники выглядят такими маленькими рядом с ним.' },
    { id: 'c5', icon: '🛡', name: 'Оборона', text: 'Щиты сомкнуты, копейщики готовы. Враг надвигается стеной. «Держать строй!» — кричит капитан.' },
    { id: 'c6', icon: '💀', name: 'После битвы', text: 'Тишина, оглушительная после рёва боя. Стон раненых. Запах крови и пота. Вы опускаетесь на колено, переводя дыхание.' },
  ],
  night: [
    { id: 'ni1', icon: '🌙', name: 'Лунная ночь', text: 'Серебристый свет луны заливает всё вокруг. Тени становятся длинными и причудливыми. Где-то воет волк.' },
    { id: 'ni2', icon: '🔮', name: 'Мистическое явление', text: 'Воздух внезапно густеет. Волосы встают дыбом. Вдалеке мерцает странный свет — неестественного, синеватого оттенка.' },
    { id: 'ni3', icon: '👻', name: 'Призрачное место', text: 'Температура падает так резко, что изо рта идёт пар. Слышен тихий плач. Свечи гаснут одна за другой.' },
    { id: 'ni4', icon: '🌌', name: 'Под звёздным небом', text: 'Вы разбили лагерь у костра. Над головой — млечный путь во всей красе. Треск костра, тихие голоса товарищей.' },
    { id: 'ni5', icon: '🎭', name: 'Зловещее знамение', text: 'Кроваво-красная луна встала над горизонтом. Собаки воют, лошади нервничают. На земле появились странные символы.' },
    { id: 'ni6', icon: '🕯', name: 'Ритуал', text: 'Круг из свечей. Шёпот на древнем языке. Запах трав и крови. В центре — алтарь, покрытый рунами.' },
  ],
};

const LOOT_CATEGORIES = {
  all: { label: 'Все', icon: '📦' },
  potion: { label: 'Зелья', icon: '🧪' },
  weapon: { label: 'Оружие', icon: '⚔' },
  armor: { label: 'Доспехи', icon: '🛡' },
  accessory: { label: 'Амулеты', icon: '💍' },
  chest: { label: 'Сундуки', icon: '📦' },
  magic: { label: 'Магия', icon: '✨' },
  resource: { label: 'Ресурсы', icon: '💰' },
};

const LOOT_ITEMS = [
  { id: 'potion_healing', name: 'Зелье лечения', icon: '🧪', category: 'potion', rarity: 'common', desc: 'Восстанавливает 2d4+2 HP.' },
  { id: 'potion_greater_heal', name: 'Зелье большого лечения', icon: '🧪', category: 'potion', rarity: 'uncommon', desc: 'Восстанавливает 4d4+4 HP.' },
  { id: 'potion_superior_heal', name: 'Зелье превосходного лечения', icon: '🧪', category: 'potion', rarity: 'rare', desc: 'Восстанавливает 8d4+8 HP.' },
  { id: 'potion_mana', name: 'Зелье маны', icon: '🫧', category: 'potion', rarity: 'common', desc: 'Восстанавливает ячейки заклинаний.' },
  { id: 'potion_invisibility', name: 'Зелье невидимости', icon: '💨', category: 'potion', rarity: 'rare', desc: 'Делает существо невидимым на 1 час.' },
  { id: 'potion_speed', name: 'Зелье скорости', icon: '⚡', category: 'potion', rarity: 'very-rare', desc: 'Удваивает скорость на 1 минуту.' },
  { id: 'potion_fly', name: 'Зелье полёта', icon: '🪽', category: 'potion', rarity: 'uncommon', desc: 'Позволяет летать в течение 1 часа.' },
  { id: 'potion_poison', name: 'Зелье яда', icon: '☠', category: 'potion', rarity: 'uncommon', desc: '1d10 урона ядом.' },
  { id: 'sword_long', name: 'Длинный меч', icon: '⚔', category: 'weapon', rarity: 'common', desc: '1d8 рубящий урон.' },
  { id: 'sword_flame', name: 'Меч пылающего пламени', icon: '🗡', category: 'weapon', rarity: 'rare', desc: '+2d6 урона огнём.' },
  { id: 'sword_holy', name: 'Святой мститель', icon: '🗡', category: 'weapon', rarity: 'legendary', desc: 'Легендарный меч. +3 к броскам.' },
  { id: 'bow_long', name: 'Длинный лук', icon: '🏹', category: 'weapon', rarity: 'common', desc: '1d8 колющий урон.' },
  { id: 'bow_elven', name: 'Эльфийский лук', icon: '🏹', category: 'weapon', rarity: 'rare', desc: '+1 к броскам.' },
  { id: 'dagger_poison', name: 'Отравленный кинжал', icon: '🗡', category: 'weapon', rarity: 'uncommon', desc: '1d4+доп. яд.' },
  { id: 'axe_battle', name: 'Боевой топор', icon: '🪓', category: 'weapon', rarity: 'common', desc: '1d8 рубящий урон.' },
  { id: 'staff_arcane', name: 'Посох тайной магии', icon: '🪄', category: 'weapon', rarity: 'rare', desc: '+1 к спасброскам заклинаний.' },
  { id: 'crossbow_hand', name: 'Ручной арбалет', icon: '🏹', category: 'weapon', rarity: 'common', desc: '1d6 колющий урон.' },
  { id: 'hammer_thunder', name: 'Молот грома', icon: '🔨', category: 'weapon', rarity: 'very-rare', desc: 'Оглушает цель на 1 раунд.' },
  { id: 'armor_chain', name: 'Кольчужная броня', icon: '🛡', category: 'armor', rarity: 'common', desc: 'КД 16.' },
  { id: 'armor_plate', name: 'Латный доспех', icon: '🛡', category: 'armor', rarity: 'uncommon', desc: 'КД 18.' },
  { id: 'shield_wooden', name: 'Деревянный щит', icon: '🛡', category: 'armor', rarity: 'common', desc: '+2 к КД.' },
  { id: 'shield_lion', name: 'Щит львиного рыка', icon: '🛡', category: 'armor', rarity: 'rare', desc: '+2 к КД. Отталкивание.' },
  { id: 'helmet_dragon', name: 'Шлем драконьей стражи', icon: '⛑', category: 'armor', rarity: 'rare', desc: 'Сопротивление огню.' },
  { id: 'boots_elven', name: 'Эльфийские сапоги', icon: '👢', category: 'armor', rarity: 'uncommon', desc: 'Бесшумное передвижение.' },
  { id: 'cloak_protection', name: 'Плащ защиты', icon: '🧥', category: 'armor', rarity: 'rare', desc: '+1 к КД и спасброскам.' },
  { id: 'gloves_dexterity', name: 'Перчатки ловкости', icon: '🧤', category: 'armor', rarity: 'uncommon', desc: 'Устанавливают ловкость 19.' },
  { id: 'amulet_health', name: 'Амулет здоровья', icon: '📿', category: 'accessory', rarity: 'uncommon', desc: 'Устанавливает телосложение 19.' },
  { id: 'amulet_planes', name: 'Амулет межпланарности', icon: '🌀', category: 'accessory', rarity: 'legendary', desc: 'Перемещение между планами.' },
  { id: 'ring_protection', name: 'Кольцо защиты', icon: '💍', category: 'accessory', rarity: 'rare', desc: '+1 к КД и спасброскам.' },
  { id: 'ring_invisibility', name: 'Кольцо невидимости', icon: '💍', category: 'accessory', rarity: 'legendary', desc: 'Невидимость по желанию.' },
  { id: 'ring_regeneration', name: 'Кольцо регенерации', icon: '💍', category: 'accessory', rarity: 'legendary', desc: 'Восстанавливает 1d6 HP каждый ход.' },
  { id: 'periapt_wound', name: 'Амулет закрытия ран', icon: '📿', category: 'accessory', rarity: 'uncommon', desc: 'Лечение на максимум.' },
  { id: 'brooch_shielding', name: 'Брошь ограждения', icon: '🔰', category: 'accessory', rarity: 'rare', desc: 'Преимущество на спасброски.' },
  { id: 'stone_good_luck', name: 'Камень удачи', icon: '🪨', category: 'accessory', rarity: 'legendary', desc: '+1 ко всем проверкам.' },
  { id: 'chest_wooden', name: 'Деревянный сундук', icon: '📦', category: 'chest', rarity: 'common', desc: 'Обычный сундук.', isLootChest: true, lootPool: 'basic' },
  { id: 'chest_locked', name: 'Запертый сундук', icon: '🔒', category: 'chest', rarity: 'uncommon', desc: 'Замок (КС 15).', isLootChest: true, lootPool: 'valuable' },
  { id: 'chest_treasure', name: 'Сундук с сокровищами', icon: '💎', category: 'chest', rarity: 'rare', desc: 'Блестит от золота!', isLootChest: true, lootPool: 'treasure' },
  { id: 'chest_trapped', name: 'Сундук с ловушкой', icon: '⚠', category: 'chest', rarity: 'rare', desc: 'Осторожно! Ловушка.', isLootChest: true, lootPool: 'trapped' },
  { id: 'chest_ancient', name: 'Древний сундук', icon: '🗝', category: 'chest', rarity: 'very-rare', desc: 'Покрыт рунами.', isLootChest: true, lootPool: 'ancient' },
  { id: 'bag_holding', name: 'Сума хранения', icon: '👜', category: 'chest', rarity: 'rare', desc: 'Вмещает до 250 кг.' },
  { id: 'scroll_fireball', name: 'Свиток огненного шара', icon: '📜', category: 'magic', rarity: 'rare', desc: '8d6 урона огнём.' },
  { id: 'scroll_resurrection', name: 'Свиток воскрешения', icon: '📜', category: 'magic', rarity: 'legendary', desc: 'Воскрешает существо.' },
  { id: 'book_spells', name: 'Книга заклинаний', icon: '📕', category: 'magic', rarity: 'rare', desc: '1d4+3 заклинания.' },
  { id: 'crystal_arcane', name: 'Тайный кристалл', icon: '💠', category: 'magic', rarity: 'uncommon', desc: 'Фокусировка для заклинателей.' },
  { id: 'orb_dragon', name: 'Драконья сфера', icon: '🔮', category: 'magic', rarity: 'legendary', desc: 'Призывает дракона-призрака.' },
  { id: 'rune_warding', name: 'Руна ограждения', icon: '🛡', category: 'magic', rarity: 'rare', desc: 'Сигнализирует о проникновении.' },
  { id: 'wand_magic_missile', name: 'Жезл магической стрелы', icon: '🪄', category: 'magic', rarity: 'uncommon', desc: '3 заряда в день.' },
  { id: 'gold_pile', name: 'Куча золота', icon: '💰', category: 'resource', rarity: 'common', desc: '50-300 золотых монет.' },
  { id: 'gems', name: 'Драгоценные камни', icon: '💎', category: 'resource', rarity: 'uncommon', desc: 'Набор из 1d6 камней.' },
  { id: 'key_iron', name: 'Железный ключ', icon: '🗝', category: 'resource', rarity: 'common', desc: 'Открывает замок.' },
  { id: 'map_treasure', name: 'Карта сокровищ', icon: '🗺', category: 'resource', rarity: 'uncommon', desc: 'Ведёт к тайнику.' },
  { id: 'torch', name: 'Факел', icon: '🔥', category: 'resource', rarity: 'common', desc: 'Освещает радиус 6 м.' },
];

const LOOT_POOLS = {
  basic: [
    { itemId: 'gold_pile', chance: 0.8, qty: [1, 2] },
    { itemId: 'torch', chance: 0.5, qty: [1, 3] },
    { itemId: 'key_iron', chance: 0.3, qty: [1, 1] },
    { itemId: 'potion_healing', chance: 0.4, qty: [1, 2] },
  ],
  valuable: [
    { itemId: 'gold_pile', chance: 1.0, qty: [2, 4] },
    { itemId: 'gems', chance: 0.7, qty: [1, 3] },
    { itemId: 'potion_healing', chance: 0.6, qty: [1, 2] },
    { itemId: 'potion_greater_heal', chance: 0.3, qty: [1, 1] },
    { itemId: 'scroll_fireball', chance: 0.2, qty: [1, 1] },
    { itemId: 'ring_protection', chance: 0.15, qty: [1, 1] },
  ],
  treasure: [
    { itemId: 'gold_pile', chance: 1.0, qty: [3, 6] },
    { itemId: 'gems', chance: 1.0, qty: [2, 5] },
    { itemId: 'potion_greater_heal', chance: 0.5, qty: [1, 2] },
    { itemId: 'potion_superior_heal', chance: 0.3, qty: [1, 1] },
    { itemId: 'sword_flame', chance: 0.2, qty: [1, 1] },
    { itemId: 'amulet_health', chance: 0.25, qty: [1, 1] },
    { itemId: 'scroll_resurrection', chance: 0.1, qty: [1, 1] },
  ],
  trapped: [
    { itemId: 'gold_pile', chance: 1.0, qty: [2, 5] },
    { itemId: 'gems', chance: 0.8, qty: [2, 4] },
    { itemId: 'potion_greater_heal', chance: 0.5, qty: [1, 2] },
    { itemId: 'sword_holy', chance: 0.1, qty: [1, 1] },
    { itemId: 'ring_regeneration', chance: 0.1, qty: [1, 1] },
    { itemId: 'stone_good_luck', chance: 0.08, qty: [1, 1] },
  ],
  ancient: [
    { itemId: 'gold_pile', chance: 1.0, qty: [5, 10] },
    { itemId: 'gems', chance: 1.0, qty: [4, 8] },
    { itemId: 'potion_superior_heal', chance: 0.7, qty: [1, 2] },
    { itemId: 'potion_speed', chance: 0.5, qty: [1, 1] },
    { itemId: 'sword_holy', chance: 0.25, qty: [1, 1] },
    { itemId: 'ring_invisibility', chance: 0.2, qty: [1, 1] },
    { itemId: 'amulet_planes', chance: 0.15, qty: [1, 1] },
    { itemId: 'orb_dragon', chance: 0.1, qty: [1, 1] },
    { itemId: 'stone_good_luck', chance: 0.2, qty: [1, 1] },
  ],
};

const RANDOM_TABLES = {
  encounter_easy: { name: 'Лёгкое столкновение', icon: '🐺', entries: [
    { name: 'Стая волков', icon: '🐺', desc: '2d4 волков', monsters: ['Волк'], count: [2, 6] },
    { name: 'Бандиты-новички', icon: '🗡', desc: '3 бандита', monsters: ['Бандит'], count: [3, 3] },
    { name: 'Гоблинский дозор', icon: '👺', desc: '4 гоблина', monsters: ['Гоблин'], count: [4, 4] },
    { name: 'Гигантские крысы', icon: '🐀', desc: '3d4 крыс', monsters: ['Крыса'], count: [3, 12] },
    { name: 'Скелеты-стражи', icon: '💀', desc: '2d6 скелетов', monsters: ['Скелет'], count: [2, 12] },
    { name: 'Блуждающий торговец', icon: '🧳', desc: 'Один NPC-торговец', monsters: ['Торговец'], count: [1, 1] },
  ]},
  encounter_medium: { name: 'Среднее столкновение', icon: '⚔', entries: [
    { name: 'Огра-одиночка', icon: '👹', desc: 'Огр с дубиной', monsters: ['Огр'], count: [1, 1] },
    { name: 'Вампирские отпрыски', icon: '🧛', desc: '2d4 отпрыска', monsters: ['Вампир'], count: [2, 8] },
    { name: 'Минотавр', icon: '🐂', desc: 'Один минотавр', monsters: ['Минотавр'], count: [1, 1] },
    { name: 'Гарпии', icon: '🦅', desc: '3d4 гарпии', monsters: ['Гарпия'], count: [3, 12] },
  ]},
  encounter_hard: { name: 'Сложное столкновение', icon: '🐉', entries: [
    { name: 'Молодой дракон', icon: '🐲', desc: 'Молодой красный дракон', monsters: ['Дракон'], count: [1, 1] },
    { name: 'Лич с охраной', icon: '☠', desc: 'Лич и 6 скелетов', monsters: ['Лич'], count: [7, 7] },
    { name: 'Вампир-лорд', icon: '🧛', desc: 'Вампир и 2d4 отпрысков', monsters: ['Вампир-лорд'], count: [3, 9] },
  ]},
  trap: { name: 'Случайная ловушка', icon: '⚠', entries: [
    { name: 'Яма с кольями', icon: '🕳', desc: 'КС 15 Лов. 2d10 колющего' },
    { name: 'Отравленные дротики', icon: '🎯', desc: 'КС 14 Лов. 1d10 яда' },
    { name: 'Огненный всполох', icon: '🔥', desc: 'КС 15 Лов. 4d6 огнём' },
    { name: 'Газ сна', icon: '💤', desc: 'КС 13 Тел. Сон 1d4 часа' },
    { name: 'Обрушивающийся потолок', icon: '⬇', desc: 'КС 15 Сил. 2d10 дробящего' },
    { name: 'Руна взрыва', icon: '💥', desc: 'КС 16 Лов. 5d8 силом' },
  ]},
  event: { name: 'Случайное событие', icon: '🎭', entries: [
    { name: 'Землетрясение', icon: '🌋', desc: 'КС 10 Лов, иначе сбит' },
    { name: 'Внезапный туман', icon: '🌫', desc: 'Видимость 3 м на 1d4 часа' },
    { name: 'Странствующий торговец', icon: '🧳', desc: 'Дружелюбный торговец' },
    { name: 'Заблудившийся путник', icon: '🧙', desc: 'Просит помощи' },
    { name: 'Находка', icon: '💎', desc: '1d100 зм и предмет' },
    { name: 'Магический всплеск', icon: '✨', desc: 'Заклинания усиливаются' },
  ]},
  weather: { name: 'Смена погоды', icon: '⛅', entries: [
    { name: 'Ясно', icon: '☀', desc: 'Хорошая видимость' },
    { name: 'Лёгкий дождь', icon: '🌦', desc: 'Помеха на Восприятие' },
    { name: 'Гроза', icon: '⛈', desc: 'Помеха, шум' },
    { name: 'Густой туман', icon: '🌫', desc: 'Видимость 6 м' },
    { name: 'Снежная буря', icon: '🌨', desc: 'Сложная местность' },
    { name: 'Лунное затмение', icon: '🌑', desc: 'Нежить в преимуществе' },
  ]},
  npc: { name: 'Случайный NPC', icon: '👤', entries: [
    { name: 'Странствующий бард', icon: '🎵', desc: 'Знает слухи' },
    { name: 'Раненый рыцарь', icon: '🛡', desc: 'Просит помощи' },
    { name: 'Таинственный маг', icon: '🧙', desc: 'Предлагает сделку' },
    { name: 'Торговец редкостями', icon: '🧳', desc: '1d3 редких предмета' },
    { name: 'Дух-проводник', icon: '👻', desc: 'Указывает путь' },
    { name: 'Наёмник', icon: '⚔', desc: '2 зм/день' },
  ]},
};

const MAP_MAX = 4000;
const MAX_LOG_ENTRIES = 500;
